name: hesabdar_promax
description: نرم افزار جامع و هوشمند حسابداری و مدیریت فروشگاه موبایل پرومکس
publish_to: 'none'
version: 1.6.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  qr_code_scanner_plus: ^2.0.7
  permission_handler: ^11.3.1
  http: ^1.2.0
  pdf: ^3.10.8
  printing: ^5.13.0
  shamsi_date: ^1.0.1
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.0.0
  shimmer: ^3.0.0

flutter:
  uses-material-design: true
