name: hesabdar_promax
description: حسابدار پرومکس چند ادمینی
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  mobile_scanner: ^5.0.0
  http: ^1.2.0
  pdf: ^3.10.8
  printing: ^5.13.0
  shamsi_date: ^1.0.1

flutter:
  uses-material-design: true
